server:
  port: 8090
  context-path: /admin
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/process
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    check-template-location: true
    cache: false
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml



    